"""Tests for MYS-109: mix-lifecycle email notifications.

Covers the event→email mapping at each state transition, recipient filtering
(unsubscribed / removed members are skipped), the one-click unsubscribe
endpoint, and the profile preference surface. Notifications are scheduled as
FastAPI background tasks; the ASGI test transport runs them before the response
returns, so the spy sender has recorded them by the time a request resolves.

Mixes are created through the autogen flow (POST /clubs seeds N *pending*
mixes), then opened via PATCH — matching real usage. The legacy POST /mixes
path defaults a mix straight to open_submission, which wouldn't exercise the
pending→open transition we notify on.
"""

import uuid
from datetime import datetime, timedelta, timezone

from sqlalchemy import select

from app.auth.jwt import create_access_token, create_unsubscribe_token
from app.models.club import Club
from app.models.club_member import ClubMember
from app.models.mix import Mix
from app.models.user import User


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #


async def _seed_user(db_session, email: str, name: str = "User") -> User:
    user = User(email=email, display_name=name)
    db_session.add(user)
    await db_session.commit()
    await db_session.refresh(user)
    return user


def _auth(user_id: uuid.UUID) -> dict[str, str]:
    return {"Authorization": f"Bearer {create_access_token(user_id)}"}


async def _create_club(client, user_id, *, total_mixes: int = 2):
    resp = await client.post(
        "/api/v1/clubs",
        json={"name": "Friday Mixtape", "total_mixes": total_mixes},
        headers=_auth(user_id),
    )
    assert resp.status_code == 201, resp.text
    return uuid.UUID(resp.json()["id"])


async def _add_member(db_session, club_id, user) -> None:
    db_session.add(ClubMember(club_id=club_id, user_id=user.id))
    await db_session.commit()


async def _mix_id(client, club_id, user_id, number: int) -> str:
    resp = await client.get(f"/api/v1/clubs/{club_id}/mixes", headers=_auth(user_id))
    assert resp.status_code == 200, resp.text
    for r in resp.json():
        if r["mix_number"] == number:
            return r["id"]
    raise AssertionError(f"mix {number} not found")


async def _advance(client, mix_id, organizer_id, state):
    # A mix can't open without a theme (MYS-211); autogenerated mixes start
    # with none, so set one in the same request that opens it.
    body = (
        {"state": state, "theme": "late summer feels"}
        if state == "open_submission"
        else {"state": state}
    )
    return await client.patch(f"/api/v1/mixes/{mix_id}", json=body, headers=_auth(organizer_id))


async def _club_with_members(client, db_session, *, n_members: int = 2, total_mixes: int = 2):
    organizer = await _seed_user(db_session, "org@example.com", "Org")
    club_id = await _create_club(client, organizer.id, total_mixes=total_mixes)
    members = []
    for i in range(n_members):
        m = await _seed_user(db_session, f"m{i}@example.com", f"M{i}")
        await _add_member(db_session, club_id, m)
        members.append(m)
    return organizer, club_id, members


# --------------------------------------------------------------------------- #
# Event → email mapping
# --------------------------------------------------------------------------- #


async def test_opening_submission_emails_all_members(client, db_session, email_spy):
    organizer, club_id, _members = await _club_with_members(client, db_session)
    rid = await _mix_id(client, club_id, organizer.id, 1)

    email_spy.sends.clear()
    resp = await _advance(client, rid, organizer.id, "open_submission")
    assert resp.status_code == 200

    recipients = {to for (to, _subj, _html) in email_spy.sends}
    assert recipients == {"org@example.com", "m0@example.com", "m1@example.com"}
    assert "open for submissions" in email_spy.sends[0][1]


async def test_voting_open_emails_all_members(client, db_session, email_spy):
    organizer, club_id, _members = await _club_with_members(client, db_session)
    rid = await _mix_id(client, club_id, organizer.id, 1)
    await _advance(client, rid, organizer.id, "open_submission")

    email_spy.sends.clear()
    await _advance(client, rid, organizer.id, "open_voting")

    assert len(email_spy.sends) == 3
    assert all("voting is open" in subj for (_to, subj, _html) in email_spy.sends)


async def test_extend_voting_emails_new_deadline(client, db_session, email_spy):
    organizer, club_id, _members = await _club_with_members(client, db_session)
    rid = await _mix_id(client, club_id, organizer.id, 1)
    await _advance(client, rid, organizer.id, "open_submission")
    await _advance(client, rid, organizer.id, "open_voting")
    current = (await client.get(f"/api/v1/mixes/{rid}", headers=_auth(organizer.id))).json()
    new_deadline = datetime.fromisoformat(current["voting_deadline"]) + timedelta(hours=4)

    email_spy.sends.clear()
    resp = await client.post(
        f"/api/v1/mixes/{rid}/extend-voting",
        json={"voting_deadline": new_deadline.isoformat()},
        headers=_auth(organizer.id),
    )
    assert resp.status_code == 200, resp.text

    recipients = {to for (to, _subj, _html) in email_spy.sends}
    assert recipients == {"org@example.com", "m0@example.com", "m1@example.com"}
    assert all("voting extended" in subj for (_to, subj, _html) in email_spy.sends)
    assert all("New deadline:" in html for (_to, _subj, html) in email_spy.sends)


async def test_closing_mix_emails_and_notifies_auto_opened_next(client, db_session, email_spy):
    organizer, club_id, _members = await _club_with_members(client, db_session, total_mixes=2)
    rid = await _mix_id(client, club_id, organizer.id, 1)
    await _advance(client, rid, organizer.id, "open_submission")
    await _advance(client, rid, organizer.id, "open_voting")
    # Mix 2 needs a theme before it can auto-open (MYS-211) — give it one now,
    # while it's still pending, so the auto-open below succeeds.
    r2_id = await _mix_id(client, club_id, organizer.id, 2)
    await client.patch(
        f"/api/v1/mixes/{r2_id}", json={"theme": "songs for the drive"}, headers=_auth(organizer.id)
    )

    email_spy.sends.clear()
    await _advance(client, rid, organizer.id, "closed")

    subjects = [subj for (_to, subj, _html) in email_spy.sends]
    # 3 members × (mix_closed for r1 + submission_open for the auto-opened r2)
    assert len(email_spy.sends) == 6
    assert sum("results are in" in s for s in subjects) == 3
    assert sum("open for submissions" in s for s in subjects) == 3


async def test_closing_mix_notifies_organizer_when_next_has_no_theme(client, db_session, email_spy):
    """A themeless next mix (MYS-211) doesn't auto-open — the organizer alone
    gets a nudge, not the whole club a submission_open they can't act on."""
    organizer, club_id, _members = await _club_with_members(client, db_session, total_mixes=2)
    rid = await _mix_id(client, club_id, organizer.id, 1)
    await _advance(client, rid, organizer.id, "open_submission")
    await _advance(client, rid, organizer.id, "open_voting")
    # Mix 2 stays themeless (autogenerated, never edited).

    email_spy.sends.clear()
    await _advance(client, rid, organizer.id, "closed")

    subjects = [subj for (_to, subj, _html) in email_spy.sends]
    # 3 members × mix_closed for r1, plus exactly one needs_theme email — to
    # the organizer only, never the other members.
    assert len(email_spy.sends) == 4
    assert sum("results are in" in s for s in subjects) == 3
    assert sum("needs a theme" in s for s in subjects) == 1
    theme_notice_recipients = {
        to for (to, subj, _html) in email_spy.sends if "needs a theme" in subj
    }
    assert theme_notice_recipients == {"org@example.com"}

    # Mix 2 is still pending — never opened — and the club has no active mix.
    db_session.expire_all()
    club = await db_session.scalar(select(Club).where(Club.id == club_id))
    r2 = await db_session.scalar(select(Mix).where(Mix.club_id == club.id, Mix.mix_number == 2))
    assert r2.state == "pending"
    assert club.current_mix == 1


async def test_closing_final_mix_emails_completion(client, db_session, email_spy):
    organizer, club_id, _members = await _club_with_members(
        client, db_session, n_members=1, total_mixes=1
    )
    rid = await _mix_id(client, club_id, organizer.id, 1)
    await _advance(client, rid, organizer.id, "open_submission")
    await _advance(client, rid, organizer.id, "open_voting")

    email_spy.sends.clear()
    await _advance(client, rid, organizer.id, "closed")

    subjects = [subj for (_to, subj, _html) in email_spy.sends]
    # 2 members (organizer + m0) × (mix_closed + club_complete)
    assert sum("results are in" in s for s in subjects) == 2
    assert sum("that's a wrap" in s for s in subjects) == 2


# --------------------------------------------------------------------------- #
# Recipient filtering
# --------------------------------------------------------------------------- #


async def test_unsubscribed_member_is_skipped(client, db_session, email_spy):
    organizer, club_id, members = await _club_with_members(client, db_session)
    members[0].email_notifications = False
    await db_session.commit()
    rid = await _mix_id(client, club_id, organizer.id, 1)

    email_spy.sends.clear()
    await _advance(client, rid, organizer.id, "open_submission")

    recipients = {to for (to, _s, _h) in email_spy.sends}
    assert recipients == {"org@example.com", "m1@example.com"}


async def test_removed_member_is_skipped(client, db_session, email_spy):
    organizer, club_id, members = await _club_with_members(client, db_session)
    lm = await db_session.scalar(select(ClubMember).where(ClubMember.user_id == members[0].id))
    lm.removed_at = datetime.now(timezone.utc)
    await db_session.commit()
    rid = await _mix_id(client, club_id, organizer.id, 1)

    email_spy.sends.clear()
    await _advance(client, rid, organizer.id, "open_submission")

    recipients = {to for (to, _s, _h) in email_spy.sends}
    assert "m0@example.com" not in recipients


# --------------------------------------------------------------------------- #
# Unsubscribe endpoint
# --------------------------------------------------------------------------- #


async def test_unsubscribe_flips_flag(client, db_session):
    user = await _seed_user(db_session, "u@example.com")
    user_id = user.id  # capture before expire_all (avoid the async lazy-load trap)
    token = create_unsubscribe_token(user_id)

    resp = await client.get(f"/api/v1/notifications/unsubscribe?token={token}")
    assert resp.status_code == 200
    assert "unsubscribed" in resp.text.lower()

    db_session.expire_all()
    refreshed = await db_session.get(User, user_id)
    assert refreshed is not None
    assert refreshed.email_notifications is False


async def test_unsubscribe_invalid_token_is_calm(client, db_session):
    user = await _seed_user(db_session, "u@example.com")
    user_id = user.id

    resp = await client.get("/api/v1/notifications/unsubscribe?token=not-a-real-token")
    assert resp.status_code == 200
    assert "didn't work" in resp.text.lower()

    db_session.expire_all()
    refreshed = await db_session.get(User, user_id)
    assert refreshed is not None
    assert refreshed.email_notifications is True  # unchanged


async def test_unsubscribe_link_present_in_email(client, db_session, email_spy):
    organizer, club_id, _members = await _club_with_members(client, db_session, n_members=1)
    rid = await _mix_id(client, club_id, organizer.id, 1)

    email_spy.sends.clear()
    await _advance(client, rid, organizer.id, "open_submission")

    _to, _subj, html = email_spy.sends[0]
    assert "/api/v1/notifications/unsubscribe?token=" in html


async def test_unsubscribe_header_present(client, db_session, email_spy):
    organizer, club_id, _members = await _club_with_members(client, db_session, n_members=1)
    rid = await _mix_id(client, club_id, organizer.id, 1)

    email_spy.sends.clear()
    email_spy.sent_headers.clear()
    await _advance(client, rid, organizer.id, "open_submission")

    headers = email_spy.sent_headers[0]
    assert headers is not None
    assert headers["List-Unsubscribe-Post"] == "List-Unsubscribe=One-Click"
    assert "/api/v1/notifications/unsubscribe?token=" in headers["List-Unsubscribe"]


# --------------------------------------------------------------------------- #
# Profile preference surface
# --------------------------------------------------------------------------- #


async def test_profile_exposes_and_updates_preference(client, db_session):
    user = await _seed_user(db_session, "u@example.com")
    me = await client.get("/api/v1/users/me", headers=_auth(user.id))
    assert me.json()["email_notifications"] is True

    patched = await client.patch(
        "/api/v1/users/me", json={"email_notifications": False}, headers=_auth(user.id)
    )
    assert patched.status_code == 200
    assert patched.json()["email_notifications"] is False
