"""Tests for MYS-159: deadline schema for datetime-based mix closing.

Covers two surfaces:

* the per-club deadline windows (``submission_window_hours`` /
  ``voting_window_hours``) on the Clubs create/update API — defaults,
  persistence, the 4..168 hour bound (422), and explicit-null rejection; and
* the deadline *stamping* done in ``advance_mix_state`` when a mix enters
  ``open_submission`` / ``open_voting`` (manual PATCH and the auto-opened next
  mix on close), including the "don't clobber a manually set deadline" rule.

Mixes are stamped only through the PATCH state machine, so these tests drive the
auto-generated pending slate created by ``POST /clubs`` rather than the
single-create endpoint (which is born ``open_submission`` and never stamps).

Windows are hour-granular (min 4h, max 168h; default 72h = 3 days) as of the
2026-07-02 rework. See technical-design.md §6 (clubs, mixes) and the MYS-159
migration ``c7d2e9f1a4b8_deadline_schema``.
"""

import uuid
from datetime import datetime, time, timedelta, timezone
from zoneinfo import ZoneInfo

from sqlalchemy import select

from app.auth.jwt import create_access_token
from app.models.club import Club
from app.models.user import User
from app.services.deadline_scheduling import MIN_ANCHOR_LEAD

_WEEKDAY_NAMES = (
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday",
)

CLUBS_URL = "/api/v1/clubs"

# Tolerance for "deadline is about now + N hours": the server stamps with its own
# datetime.now, the test computes its expected with a slightly later one, so a
# couple of minutes of slack absorbs the request round-trip without letting a
# wrong window count sneak past.
_TOL_SECONDS = 120


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #


async def _seed_user(db_session, email: str = "org@example.com", name: str = "Org") -> User:
    user = User(email=email, display_name=name)
    db_session.add(user)
    await db_session.commit()
    await db_session.refresh(user)
    return user


def _auth(user_id: uuid.UUID) -> dict[str, str]:
    return {"Authorization": f"Bearer {create_access_token(user_id)}"}


async def _create_club(client, user_id: uuid.UUID, **overrides) -> dict:
    """Create a club via the API so its pending mix slate auto-generates."""
    body = {"name": "Deadline Club", "total_mixes": 3, "votes_per_player": 3}
    body.update(overrides)
    resp = await client.post(CLUBS_URL, headers=_auth(user_id), json=body)
    assert resp.status_code == 201, resp.text
    return resp.json()


async def _mixes(client, club_id, user_id) -> list[dict]:
    resp = await client.get(f"{CLUBS_URL}/{club_id}/mixes", headers=_auth(user_id))
    assert resp.status_code == 200, resp.text
    return resp.json()


async def _mix_by_number(client, club_id, user_id, number: int) -> dict:
    return next(r for r in await _mixes(client, club_id, user_id) if r["mix_number"] == number)


async def _patch_mix(client, mix_id, user_id, **body) -> dict:
    # A mix can't open without a theme (MYS-211); autogenerated mixes start
    # with none, so any caller opening one gets a default unless it already
    # supplied its own theme.
    if body.get("state") == "open_submission" and "theme" not in body:
        body = {**body, "theme": "late summer feels"}
    resp = await client.patch(f"/api/v1/mixes/{mix_id}", json=body, headers=_auth(user_id))
    assert resp.status_code == 200, resp.text
    return resp.json()


def _assert_matches_weekly_anchor(
    deadline_iso: str | None, tz_name: str, weekday_name: str, at_time
) -> None:
    """Assert a stamped deadline matches a weekly-anchor config (ADR 0021).

    A live "now" isn't controllable in an integration test, so this checks the
    invariants a correctly-computed anchor must satisfy — right weekday/time in
    the configured zone, and within [24h, 7d + MIN_ANCHOR_LEAD] of the moment
    it was stamped — rather than an exact timestamp.

    The upper bound is NOT simply "7 days": _next_weekly_occurrence rolls a
    same-day-but-too-soon candidate forward a full extra week (MIN_ANCHOR_LEAD),
    so when "now" lands on the anchor's own weekday just before its anchor
    time, the true gap can be up to just under 7 days + MIN_ANCHOR_LEAD. A
    tighter "7 days + 1h" bound here previously failed deterministically
    whenever a test happened to run on the anchor weekday's morning in its
    configured zone (MysteryMixClub-w790) — not flakiness, a bound that didn't
    account for real production behavior it was supposed to allow.
    """
    assert deadline_iso is not None, "expected a stamped deadline, got null"
    deadline = datetime.fromisoformat(deadline_iso)
    local = deadline.astimezone(ZoneInfo(tz_name))
    assert _WEEKDAY_NAMES[local.weekday()] == weekday_name, (
        f"expected {weekday_name}, got {_WEEKDAY_NAMES[local.weekday()]} ({deadline})"
    )
    assert local.time() == at_time
    now = datetime.now(timezone.utc)
    upper_bound = timedelta(days=7) + MIN_ANCHOR_LEAD
    # _TOL_SECONDS slack on the lower bound too: the server computes the
    # deadline, then this test's `now` is captured after the response
    # round-trip, so a raw candidate that landed exactly at the 24h minimum
    # lead would otherwise read as slightly under 24h here and fail on
    # nothing but request latency.
    lower_bound = timedelta(hours=24) - timedelta(seconds=_TOL_SECONDS)
    assert lower_bound <= (deadline - now) <= upper_bound, (
        f"deadline {deadline} is not within [{lower_bound}, {upper_bound}] of now ({now})"
    )


def _assert_about_hours(deadline_iso: str | None, expected_hours: int) -> None:
    """Assert an ISO deadline string is ~ now + expected_hours (within tolerance)."""
    assert deadline_iso is not None, "expected a stamped deadline, got null"
    deadline = datetime.fromisoformat(deadline_iso)
    expected = datetime.now(timezone.utc) + timedelta(hours=expected_hours)
    delta = abs((deadline - expected).total_seconds())
    assert delta < _TOL_SECONDS, (
        f"deadline {deadline} is {delta:.0f}s from expected {expected} (≈ now + {expected_hours}h)"
    )


# ========================================================================== #
# Club API — deadline-window fields
# ========================================================================== #


async def test_create_defaults_windows_to_72(client, db_session):
    user = await _seed_user(db_session)
    data = await _create_club(client, user.id)  # no window fields supplied
    assert data["submission_window_hours"] == 72
    assert data["voting_window_hours"] == 72


async def test_create_with_explicit_windows_persisted(client, db_session):
    user = await _seed_user(db_session)
    data = await _create_club(client, user.id, submission_window_hours=6, voting_window_hours=100)
    assert data["submission_window_hours"] == 6
    assert data["voting_window_hours"] == 100

    club_id = uuid.UUID(data["id"])
    db_session.expire_all()
    persisted = await db_session.scalar(select(Club).where(Club.id == club_id))
    assert persisted.submission_window_hours == 6
    assert persisted.voting_window_hours == 100


async def test_create_accepts_min_boundary_4(client, db_session):
    # 4h is the inclusive minimum — accepted on both fields.
    user = await _seed_user(db_session)
    data = await _create_club(client, user.id, submission_window_hours=4, voting_window_hours=4)
    assert data["submission_window_hours"] == 4
    assert data["voting_window_hours"] == 4


async def test_create_accepts_max_boundary_168(client, db_session):
    # 168h is the inclusive maximum — accepted on both fields.
    user = await _seed_user(db_session)
    data = await _create_club(client, user.id, submission_window_hours=168, voting_window_hours=168)
    assert data["submission_window_hours"] == 168
    assert data["voting_window_hours"] == 168


async def test_create_submission_window_below_min_returns_422(client, db_session):
    user = await _seed_user(db_session)
    resp = await client.post(
        CLUBS_URL,
        headers=_auth(user.id),
        json={"name": "L", "submission_window_hours": 3},
    )
    assert resp.status_code == 422, resp.text


async def test_create_submission_window_above_max_returns_422(client, db_session):
    user = await _seed_user(db_session)
    resp = await client.post(
        CLUBS_URL,
        headers=_auth(user.id),
        json={"name": "L", "submission_window_hours": 169},
    )
    assert resp.status_code == 422, resp.text


async def test_create_voting_window_below_min_returns_422(client, db_session):
    user = await _seed_user(db_session)
    resp = await client.post(
        CLUBS_URL,
        headers=_auth(user.id),
        json={"name": "L", "voting_window_hours": 3},
    )
    assert resp.status_code == 422, resp.text


async def test_create_voting_window_above_max_returns_422(client, db_session):
    user = await _seed_user(db_session)
    resp = await client.post(
        CLUBS_URL,
        headers=_auth(user.id),
        json={"name": "L", "voting_window_hours": 169},
    )
    assert resp.status_code == 422, resp.text


async def test_patch_windows_updates_and_persists(client, db_session):
    user = await _seed_user(db_session)
    data = await _create_club(client, user.id)
    club_id = uuid.UUID(data["id"])

    resp = await client.patch(
        f"{CLUBS_URL}/{club_id}",
        headers=_auth(user.id),
        json={"submission_window_hours": 12, "voting_window_hours": 168},
    )
    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert body["submission_window_hours"] == 12
    assert body["voting_window_hours"] == 168

    db_session.expire_all()
    persisted = await db_session.scalar(select(Club).where(Club.id == club_id))
    assert persisted.submission_window_hours == 12
    assert persisted.voting_window_hours == 168


async def test_patch_accepts_min_boundary_4(client, db_session):
    # 4h is the inclusive minimum — accepted on patch for both fields.
    user = await _seed_user(db_session)
    data = await _create_club(client, user.id)
    resp = await client.patch(
        f"{CLUBS_URL}/{data['id']}",
        headers=_auth(user.id),
        json={"submission_window_hours": 4, "voting_window_hours": 4},
    )
    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert body["submission_window_hours"] == 4
    assert body["voting_window_hours"] == 4


async def test_patch_accepts_max_boundary_168(client, db_session):
    # 168h is the inclusive maximum — accepted on patch for both fields.
    user = await _seed_user(db_session)
    data = await _create_club(client, user.id)
    resp = await client.patch(
        f"{CLUBS_URL}/{data['id']}",
        headers=_auth(user.id),
        json={"submission_window_hours": 168, "voting_window_hours": 168},
    )
    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert body["submission_window_hours"] == 168
    assert body["voting_window_hours"] == 168


async def test_patch_submission_window_below_min_returns_422(client, db_session):
    user = await _seed_user(db_session)
    data = await _create_club(client, user.id)
    resp = await client.patch(
        f"{CLUBS_URL}/{data['id']}",
        headers=_auth(user.id),
        json={"submission_window_hours": 3},
    )
    assert resp.status_code == 422, resp.text


async def test_patch_voting_window_above_max_returns_422(client, db_session):
    user = await _seed_user(db_session)
    data = await _create_club(client, user.id)
    resp = await client.patch(
        f"{CLUBS_URL}/{data['id']}",
        headers=_auth(user.id),
        json={"voting_window_hours": 169},
    )
    assert resp.status_code == 422, resp.text


async def test_patch_explicit_null_submission_window_returns_422(client, db_session):
    user = await _seed_user(db_session)
    data = await _create_club(client, user.id)
    resp = await client.patch(
        f"{CLUBS_URL}/{data['id']}",
        headers=_auth(user.id),
        json={"submission_window_hours": None},
    )
    assert resp.status_code == 422, resp.text


async def test_patch_explicit_null_voting_window_returns_422(client, db_session):
    user = await _seed_user(db_session)
    data = await _create_club(client, user.id)
    resp = await client.patch(
        f"{CLUBS_URL}/{data['id']}",
        headers=_auth(user.id),
        json={"voting_window_hours": None},
    )
    assert resp.status_code == 422, resp.text


# ========================================================================== #
# Deadline stamping on state transitions
# ========================================================================== #


async def test_open_submission_stamps_submission_deadline(client, db_session):
    user = await _seed_user(db_session)
    data = await _create_club(client, user.id)  # default 72/72
    club_id = data["id"]
    r1 = await _mix_by_number(client, club_id, user.id, 1)
    assert r1["state"] == "pending"
    assert r1["submission_deadline"] is None

    opened = await _patch_mix(client, r1["id"], user.id, state="open_submission")
    assert opened["state"] == "open_submission"
    _assert_about_hours(opened["submission_deadline"], 72)
    # Voting deadline is only stamped when voting opens.
    assert opened["voting_deadline"] is None


async def test_open_voting_stamps_voting_deadline(client, db_session):
    user = await _seed_user(db_session)
    data = await _create_club(client, user.id)  # default 72/72
    club_id = data["id"]
    r1 = await _mix_by_number(client, club_id, user.id, 1)

    await _patch_mix(client, r1["id"], user.id, state="open_submission")
    voting = await _patch_mix(client, r1["id"], user.id, state="open_voting")
    assert voting["state"] == "open_voting"
    _assert_about_hours(voting["voting_deadline"], 72)


async def test_open_submission_does_not_clobber_manual_deadline(client, db_session):
    # An organizer who sets a submission_deadline explicitly while the mix is
    # pending keeps it when the mix opens (MYS-159 no-clobber).
    user = await _seed_user(db_session)
    data = await _create_club(client, user.id)  # default 72h window
    club_id = data["id"]
    r1 = await _mix_by_number(client, club_id, user.id, 1)

    manual = datetime.now(timezone.utc) + timedelta(hours=240)
    await _patch_mix(client, r1["id"], user.id, submission_deadline=manual.isoformat())
    opened = await _patch_mix(client, r1["id"], user.id, state="open_submission")
    # Still ~240h out, not the 72h club default — the manual value stuck.
    _assert_about_hours(opened["submission_deadline"], 240)


async def test_open_voting_does_not_clobber_manual_voting_deadline(client, db_session):
    user = await _seed_user(db_session)
    data = await _create_club(client, user.id)  # default 72h window
    club_id = data["id"]
    r1 = await _mix_by_number(client, club_id, user.id, 1)

    await _patch_mix(client, r1["id"], user.id, state="open_submission")
    manual = datetime.now(timezone.utc) + timedelta(hours=288)
    await _patch_mix(client, r1["id"], user.id, voting_deadline=manual.isoformat())
    voting = await _patch_mix(client, r1["id"], user.id, state="open_voting")
    _assert_about_hours(voting["voting_deadline"], 288)


# ========================================================================== #
# Auto-open path — the next mix gets its own submission deadline
# ========================================================================== #


async def test_closing_nonfinal_mix_stamps_next_mix_submission_deadline(client, db_session):
    # total_mixes=2 so mix 1 is non-final: closing it auto-opens mix 2, which
    # must get its own submission_deadline stamped from the club window.
    user = await _seed_user(db_session)
    data = await _create_club(client, user.id, total_mixes=2)  # default 72h
    club_id = data["id"]
    r1 = await _mix_by_number(client, club_id, user.id, 1)
    r2_pending = await _mix_by_number(client, club_id, user.id, 2)
    # A mix can't auto-open without a theme (MYS-211) — give mix 2 one while
    # it's still pending, so closing mix 1 below actually opens it.
    await _patch_mix(client, r2_pending["id"], user.id, theme="songs for the drive")

    await _patch_mix(client, r1["id"], user.id, state="open_submission")
    await _patch_mix(client, r1["id"], user.id, state="open_voting")
    closed = await _patch_mix(client, r1["id"], user.id, state="closed")
    assert closed["state"] == "closed"

    r2 = await _mix_by_number(client, club_id, user.id, 2)
    assert r2["state"] == "open_submission"
    _assert_about_hours(r2["submission_deadline"], 72)


# ========================================================================== #
# Custom club config drives the stamp windows
# ========================================================================== #


async def test_custom_windows_reflected_in_stamps(client, db_session):
    user = await _seed_user(db_session)
    # 102h = 4 days 6 hours (a non-day-aligned window); 4h = the minimum.
    data = await _create_club(client, user.id, submission_window_hours=102, voting_window_hours=4)
    club_id = data["id"]
    r1 = await _mix_by_number(client, club_id, user.id, 1)

    opened = await _patch_mix(client, r1["id"], user.id, state="open_submission")
    _assert_about_hours(opened["submission_deadline"], 102)

    voting = await _patch_mix(client, r1["id"], user.id, state="open_voting")
    _assert_about_hours(voting["voting_deadline"], 4)


async def test_next_mix_stamp_uses_club_window_not_default(client, db_session):
    # The auto-opened mix's deadline must follow the club's custom window too,
    # not a hardcoded default.
    user = await _seed_user(db_session)
    data = await _create_club(
        client, user.id, total_mixes=2, submission_window_hours=48, voting_window_hours=120
    )
    club_id = data["id"]
    r1 = await _mix_by_number(client, club_id, user.id, 1)
    r2_pending = await _mix_by_number(client, club_id, user.id, 2)
    await _patch_mix(client, r2_pending["id"], user.id, theme="songs for the drive")

    await _patch_mix(client, r1["id"], user.id, state="open_submission")
    await _patch_mix(client, r1["id"], user.id, state="open_voting")
    await _patch_mix(client, r1["id"], user.id, state="closed")

    r2 = await _mix_by_number(client, club_id, user.id, 2)
    _assert_about_hours(r2["submission_deadline"], 48)


# ========================================================================== #
# Weekly-anchor deadline mode (ADR 0021, MysteryMixClub-z845)
# ========================================================================== #

_WEEKLY_ANCHOR_FIELDS = {
    "timezone": "America/New_York",
    "submission_weekday": "tuesday",
    "submission_time": "12:00:00",
    "voting_weekday": "saturday",
    "voting_time": "12:00:00",
}


async def test_create_defaults_to_duration_mode(client, db_session):
    user = await _seed_user(db_session)
    data = await _create_club(client, user.id)
    assert data["deadline_mode"] == "duration"
    assert data["timezone"] == "UTC"
    assert data["submission_weekday"] is None
    assert data["voting_weekday"] is None


async def test_create_weekly_anchor_persists_full_schedule(client, db_session):
    user = await _seed_user(db_session)
    data = await _create_club(
        client, user.id, deadline_mode="weekly_anchor", **_WEEKLY_ANCHOR_FIELDS
    )
    assert data["deadline_mode"] == "weekly_anchor"
    assert data["timezone"] == "America/New_York"
    assert data["submission_weekday"] == "tuesday"
    assert data["submission_time"] == "12:00:00"
    assert data["voting_weekday"] == "saturday"
    assert data["voting_time"] == "12:00:00"

    club_id = uuid.UUID(data["id"])
    db_session.expire_all()
    persisted = await db_session.scalar(select(Club).where(Club.id == club_id))
    assert persisted.deadline_mode == "weekly_anchor"
    assert persisted.timezone == "America/New_York"
    assert persisted.submission_weekday == 1  # tuesday, Monday=0
    assert persisted.voting_weekday == 5  # saturday


async def test_create_weekly_anchor_missing_field_returns_422(client, db_session):
    user = await _seed_user(db_session)
    incomplete = dict(_WEEKLY_ANCHOR_FIELDS)
    del incomplete["voting_time"]
    resp = await client.post(
        CLUBS_URL,
        headers=_auth(user.id),
        json={"name": "L", "deadline_mode": "weekly_anchor", **incomplete},
    )
    assert resp.status_code == 422, resp.text


async def test_create_weekly_anchor_invalid_timezone_returns_422(client, db_session):
    user = await _seed_user(db_session)
    bad = dict(_WEEKLY_ANCHOR_FIELDS)
    bad["timezone"] = "Nowhere/Fake"
    resp = await client.post(
        CLUBS_URL,
        headers=_auth(user.id),
        json={"name": "L", "deadline_mode": "weekly_anchor", **bad},
    )
    assert resp.status_code == 422, resp.text


async def test_create_invalid_weekday_name_returns_422(client, db_session):
    user = await _seed_user(db_session)
    bad = dict(_WEEKLY_ANCHOR_FIELDS)
    bad["submission_weekday"] = "funday"
    resp = await client.post(
        CLUBS_URL,
        headers=_auth(user.id),
        json={"name": "L", "deadline_mode": "weekly_anchor", **bad},
    )
    assert resp.status_code == 422, resp.text


async def test_patch_switches_club_into_weekly_anchor_mode(client, db_session):
    user = await _seed_user(db_session)
    data = await _create_club(client, user.id)  # duration mode by default
    resp = await client.patch(
        f"{CLUBS_URL}/{data['id']}",
        headers=_auth(user.id),
        json={"deadline_mode": "weekly_anchor", **_WEEKLY_ANCHOR_FIELDS},
    )
    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert body["deadline_mode"] == "weekly_anchor"
    assert body["submission_weekday"] == "tuesday"


async def test_patch_switch_to_weekly_anchor_without_full_schedule_returns_422(client, db_session):
    user = await _seed_user(db_session)
    data = await _create_club(client, user.id)
    resp = await client.patch(
        f"{CLUBS_URL}/{data['id']}",
        headers=_auth(user.id),
        json={"deadline_mode": "weekly_anchor", "timezone": "America/New_York"},
    )
    assert resp.status_code == 422, resp.text


async def test_patch_a_single_field_once_already_in_weekly_anchor_mode(client, db_session):
    # Once weekly_anchor is fully configured, adjusting just one piece (e.g. a
    # time) doesn't require resupplying the whole schedule (ADR 0021).
    user = await _seed_user(db_session)
    data = await _create_club(
        client, user.id, deadline_mode="weekly_anchor", **_WEEKLY_ANCHOR_FIELDS
    )
    resp = await client.patch(
        f"{CLUBS_URL}/{data['id']}",
        headers=_auth(user.id),
        json={"submission_time": "18:30:00"},
    )
    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert body["submission_time"] == "18:30:00"
    assert body["deadline_mode"] == "weekly_anchor"
    # Untouched fields survive.
    assert body["voting_weekday"] == "saturday"


async def test_patch_explicit_null_deadline_mode_returns_422(client, db_session):
    user = await _seed_user(db_session)
    data = await _create_club(client, user.id)
    resp = await client.patch(
        f"{CLUBS_URL}/{data['id']}",
        headers=_auth(user.id),
        json={"deadline_mode": None},
    )
    assert resp.status_code == 422, resp.text


async def test_patch_explicit_null_timezone_returns_422(client, db_session):
    user = await _seed_user(db_session)
    data = await _create_club(client, user.id)
    resp = await client.patch(
        f"{CLUBS_URL}/{data['id']}",
        headers=_auth(user.id),
        json={"timezone": None},
    )
    assert resp.status_code == 422, resp.text


async def test_weekly_anchor_stamps_deadlines_matching_the_schedule(client, db_session):
    user = await _seed_user(db_session)
    data = await _create_club(
        client, user.id, deadline_mode="weekly_anchor", **_WEEKLY_ANCHOR_FIELDS
    )
    club_id = data["id"]
    r1 = await _mix_by_number(client, club_id, user.id, 1)

    opened = await _patch_mix(client, r1["id"], user.id, state="open_submission")
    _assert_matches_weekly_anchor(
        opened["submission_deadline"], "America/New_York", "tuesday", time(12, 0)
    )

    voting = await _patch_mix(client, r1["id"], user.id, state="open_voting")
    _assert_matches_weekly_anchor(
        voting["voting_deadline"], "America/New_York", "saturday", time(12, 0)
    )
