"""create device push tokens and user push preferences

Revision ID: 22294b11b0a1
Revises: 07a9db76f961
Create Date: 2026-09-17 12:45:05.308497

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "22294b11b0a1"
down_revision: Union[str, Sequence[str], None] = "07a9db76f961"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_push_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("device_token", sa.String(), nullable=False),
        sa.Column("platform", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("platform IN ('ios')", name="ck_device_push_tokens_platform"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_device_push_tokens_device_token"),
        "device_push_tokens",
        ["device_token"],
        unique=True,
    )
    op.create_index(
        op.f("ix_device_push_tokens_user_id"), "device_push_tokens", ["user_id"], unique=False
    )
    op.add_column(
        "users",
        sa.Column(
            "push_lifecycle_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "push_deadline_reminders_enabled",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "push_deadline_reminders_enabled")
    op.drop_column("users", "push_lifecycle_enabled")
    op.drop_index(op.f("ix_device_push_tokens_user_id"), table_name="device_push_tokens")
    op.drop_index(op.f("ix_device_push_tokens_device_token"), table_name="device_push_tokens")
    op.drop_table("device_push_tokens")
    # ### end Alembic commands ###
