"""add push deadline reminder markers to mixes

Revision ID: 261e97ee359c
Revises: 22294b11b0a1
Create Date: 2026-09-17 13:06:17.729042

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "261e97ee359c"
down_revision: Union[str, Sequence[str], None] = "22294b11b0a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mixes",
        sa.Column("push_submission_reminder_sent_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "mixes",
        sa.Column("push_voting_reminder_sent_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mixes", "push_voting_reminder_sent_at")
    op.drop_column("mixes", "push_submission_reminder_sent_at")
    # ### end Alembic commands ###
