"""apple round playlists (MYS-108)

Revision ID: 9e14aa97101d
Revises: 9b4a7e2c5d81
Create Date: 2026-07-18 09:08:14.036682

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9e14aa97101d"
down_revision: Union[str, Sequence[str], None] = "9b4a7e2c5d81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apple_round_playlists",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("round_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("playlist_id", sa.String(length=255), nullable=False),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["round_id"],
            ["rounds.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("round_id", "user_id", name="uq_apple_round_playlists_round_user"),
    )
    op.create_index(
        op.f("ix_apple_round_playlists_round_id"),
        "apple_round_playlists",
        ["round_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_apple_round_playlists_user_id"), "apple_round_playlists", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_apple_round_playlists_user_id"), table_name="apple_round_playlists")
    op.drop_index(op.f("ix_apple_round_playlists_round_id"), table_name="apple_round_playlists")
    op.drop_table("apple_round_playlists")
    # ### end Alembic commands ###
