"""apple playlist name (MYS-190)

Revision ID: ad64945262e3
Revises: 9e14aa97101d
Create Date: 2026-07-18 10:43:26.002508

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ad64945262e3"
down_revision: Union[str, Sequence[str], None] = "9e14aa97101d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "apple_round_playlists", sa.Column("playlist_name", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("apple_round_playlists", "playlist_name")
    # ### end Alembic commands ###
